
import qdf
import qdf.quasar
import sys
import random
import uuid
import time
from twisted.internet import defer, protocol, reactor
print "entered test readwrite1"
EXIT_CODE = None
def setexit(code):
    global EXIT_CODE
    EXIT_CODE = code
    reactor.stop()

@defer.inlineCallbacks
def testbody(db):
    print "connected"
    TOTALPOINTS = 1000000
    PERINSERT = 1000
    INTERVAL = int(1E9/120.)
    UID = str(uuid.uuid4())
    randomdata = [(x*INTERVAL, random.random()) for x in xrange(TOTALPOINTS)]
    idx = 0
    print "random data generated"
    for i in xrange(TOTALPOINTS/PERINSERT):
        yield db.insertValues(UID, randomdata[idx:idx+PERINSERT])
        idx += PERINSERT
    time.sleep(20)
    readdata = []
    idx = 0
    print "reading data"
    for i in xrange(TOTALPOINTS/PERINSERT):
        (status, rv) = yield db.queryStandardValues(UID, i*INTERVAL*PERINSERT, (i+1)*INTERVAL*PERINSERT)
        (version, values) = rv
        readdata += [(v.time, v.value) for v in values]
    print "len readdata:",len(readdata)
    print "len insert:",len(randomdata)
    for i in xrange(len(randomdata)):
        if randomdata[i][0] != readdata[i][0]:
            print "time mismatch index",i
            break
        if randomdata[i][1] != readdata[i][1]:
            print "value mismatch index",i
            break
    else:
        print "lists match"
        setexit(0)
        return
    setexit(1)
    return    

def onFail(param):
    print "Encountered error: ", param
    setexit(2)

def entrypoint():
    print "in entrypoint"
    try:
        q = qdf.quasar.connectToArchiver("localhost", 4410)
        q.addCallback(testbody)
        q.addErrback(onFail)
    except Exception as e:
        print "ex: ",e
        setexit(1)

reactor.callWhenRunning(entrypoint)
reactor.run()
if EXIT_CODE == None:
    EXIT_CODE = 42
if EXIT_CODE != 0:
    sys.exit(EXIT_CODE)
else:
    !rm FAILURE
